### ISSUE TITLE
Defining parent-child relationships between teams (Teams & Sub-Teams)

### ISSUE THREAD

**Issue by jwlusby** [PagerDuty/terraform-provider-pagerduty#207]
This may not be an issue and may just be user error. Is there a way to define a parent-child relationship between teams?

As in this example where I have a team "Support Team" composed of two sub-teams "Sub-Team" A and "Sub-Team B"

```
Support Team
 |___Sub-Team A
 |___Sub-Team B
```

### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
- pagerduty_team

**Comment by stmcallister** [comment]
This is currently supported by the PagerDuty API using the `parent` attribute on the `team` object, but not in the provider today.

**Comment by stmcallister** [comment]
Just an update on this issue. It appears there is a bug in the `teams` API that isn't allowing the creation of parent relationships. Will keep this thread updated as I learn more.

**Comment by drastawi** [comment]
Hey @stmcallister @jwlusby I just asked the PagerDuty folks and they confirmed the sub team/parent functionality is fully fixed now. I tested manually and it seems to work fine for me.

**Comment by stmcallister** [comment]
Hi @drastawi, I'm still experiencing the same issues as before. When making a POST request to `/teams` and including the `parent` object, the parent object does not get created. I've put a request in to the team responsible for the `/teams` endpoint to address this issue. As mentioned, I'll keep you all posted on any updates.

**Comment by stmcallister** [comment]
This feature was added with v1.9.6 of the provider. Going to close the issue. Please repost if you have further questions.
