### ISSUE TITLE
2.4.0 fails for pagerduty_schedule on time_zones that work in lower versions

### ISSUE THREAD

**Issue by kylesloan** [PagerDuty/terraform-provider-pagerduty#485]
Updating our schedule to include a new user after not touching for many months, I was getting `Error: unknown time zone America/New_York` with the module version of 2.4.0.  I tried multiple versions of terraform and then tried different module versions for pagerduty.

My finding was that on terraform 1.1.19 that pagerduty 2.3.0 worked, but pagerduty 2.4.0 threw the unknown timezone error

```
- Finding pagerduty/pagerduty versions matching "~> 2.2"...
- Installing pagerduty/pagerduty v2.4.0...
- Installed pagerduty/pagerduty v2.4.0 (signed by a HashiCorp partner, key ID 027C6DD1F0707B45)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: unknown time zone America/New_York

  with pagerduty_schedule.a-schedule,
  on schedules.tf line 3, in resource "pagerduty_schedule" "a-schedule":
   3:   time_zone   = "America/New_York"


Error: unknown time zone America/Chicago

  with pagerduty_schedule.b-schedule,
  on schedules.tf line 22, in resource "pagerduty_schedule" "b-schedule":
  22:   time_zone   = "America/Chicago"
  ```

**Comment by stmcallister** [comment]
This should have been addressed in v2.4.1. Can upgrade your version of the provider and verify that the timezone issue is fixed?

**Comment by anthonyscata-wesfarmers** [comment]
> This should have been addressed in v2.4.1. Can upgrade your version of the provider and verify that the timezone issue is fixed?

I added a comment to https://github.com/PagerDuty/terraform-provider-pagerduty/issues/477#issuecomment-1109144710 where i am still seeing this issue in `v2.4.1`

**Comment by stmcallister** [comment]
Hello all! Great news! We just pushed release [v2.4.2](https://github.com/PagerDuty/terraform-provider-pagerduty/releases/tag/v2.4.2). I just tested it on Windows and can confirm that it fixes this issue. Please give that version a try and let us know if you're still having troubles.

**Comment by stmcallister** [comment]
Going to close. Please post again if you have any further issues!
